// examples/vue/src/components/HeroEdit.vue
<template>
  <div id="edit-box" class="hero-edit box">
    <h4>Edit</h4>
    <div class="alert" v-if="!synced">
      <h4>Warning:</h4>
      <p>
        Someone else has
        <b>changed</b> this document. If you click save, you will overwrite the changes.
      </p>
      <button v-on:click="resync()">resync</button>
    </div>
    <div class="alert deleted" v-if="hero.deleted">
      <h4>Error:</h4>
      <p>
        Someone else has
        <b>deleted</b> this document. You can not save anymore.
      </p>
    </div>
    <h5>
      <div class="color-box" v-bind:style="{ backgroundColor: hero.color }"></div>
      {{hero.name}}
    </h5>HP:
    <input
      id="hp-edit-input"
      type="number"
      v-model.number="formData"
      min="0"
      v-bind:max="hero.maxHP"
      name="hp"
    >
    <br>
    <button v-on:click="cancel()">cancel</button>
    <button id="edit-submit-button" v-on:click="submit()" v-if="!hero.deleted">submit</button>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import DatabaseService from '../services/Database.service';
import { RxHeroDocument, RxHeroesDatabase } from '../RxDB';
import { skip, map, first } from 'rxjs/operators';

@Component({})
export default class HeroEdit extends Vue {
  @Prop() private hero!: RxHeroDocument;

  private synced: boolean = true;
  private deleted: boolean = false;
  private formData: number = 0;

  public async mounted() {
    console.log('HeroEdit.mounted()');
    console.dir(this.hero);
    console.log(this.hero.hp);
    this.formData = this.hero.hp;
    this.hero.$.pipe(
      skip(1),
      first(),
      map(() => false)
    )
      .toPromise()
      .then((v) => (this.synced = v));

    this.hero.deleted$
      .pipe(first())
      .toPromise()
      .then(() => (this.deleted = true));
  }

  public async submit() {
    console.log('heroEdit.submit()');
    await this.hero.atomicSet('hp', this.formData);
    this.$emit('submit');
  }
  public resync() {
    console.log('heroEdit.resync()');
    this.formData = this.hero.hp;
    this.synced = true;
  }
  public cancel() {
    console.log('heroEdit.cancel()');
    this.$emit('cancel');
  }
}
</script>


<style scoped lang="less">
.hero-edit {
  position: fixed;
  z-index: 10;
  width: 70%;
  margin-left: 10%;
  min-height: 200px;
  margin-top: -5px;
  padding: 20px;
}

.alert {
  border-style: solid;
  border-width: 2px;
  border-radius: 10px;
  padding: 8px;
  border-color: #e0e021;

  &.deleted {
    border-color: red;
  }

  h4 {
    padding: 0;
    margin: 0;
  }
}

.color-box {
  width: 20px;
  height: 20px;
  float: left;
  margin-right: 11px;
  border-radius: 2px;
  border-width: 1px;
  border-style: solid;
  border-color: grey;
}
</style>

// examples/angular/src/app/components/hero-edit/hero-edit.component.ts
import {
    Component,
    Input,
    Output,
    EventEmitter,
    OnInit,
    ChangeDetectorRef
} from '@angular/core';
import {
    Subscription
} from 'rxjs';
import {
    skip
} from 'rxjs/operators';

@Component({
    selector: 'hero-edit',
    templateUrl: './hero-edit.component.html',
    styleUrls: ['./hero-edit.component.less'],
    providers: [],
})
export class HeroEditComponent implements OnInit {

    @Input('hero') hero: any;
    @Output('done') done = new EventEmitter();

    public synced: Boolean = true;
    public formValue = 0;
    private subs: Subscription[] = [];

    constructor(
        private _cdr: ChangeDetectorRef
    ) {
        this.synced = true;
    }

    ngOnInit() {
        this.formValue = this.hero.hp;
        this.subs.push(
            this.hero.$
                .pipe(
                    skip(1)
                )
                .subscribe(() => {
                    this.synced = false;
                    this._cdr.detectChanges();
                })
        );
    }

    async submit() {
        await this.hero.atomicSet('hp', this.formValue);
        this.done.emit(true);
    }

    resync() {
        this.formValue = this.hero.hp;
        this.synced = true;
        this._cdr.detectChanges();
    }

    async cancel() {
        this.done.emit(false);
    }

    ngOnDestroy() {
        this.subs.forEach(sub => sub.unsubscribe());
    }
}

<mat-card *ngIf="hero" class="hero-edit-component">
    <mat-card-subtitle>Edit</mat-card-subtitle>

    <div class="alert" *ngIf="!synced">
        <h4>Warning:</h4>
        <p>Someone else has <b>changed</b> this document. If you click save, you will overwrite the changes.</p>
        <button mat-raised-button color="primary" (click)=resync()>resync</button>
    </div>

    <div class="alert deleted" *ngIf="(hero.deleted$ | async)">
        <h4>Error:</h4>
        <p>Someone else has <b>deleted</b> this document. You can not save anymore.</p>
    </div>

    <h5>
      <div class="color-box" [style.background-color]="hero.color"></div>
      {{hero.name}}
    </h5>


    <mat-form-field>
        HP: <input matInput type="number" [(ngModel)]="formValue" min="0" [max]="hero.maxHP" name="hp" />
    </mat-form-field>

    <br />
    <button mat-raised-button color="primary" (click)="cancel()">cancel</button>
    <button *ngIf="!(hero.deleted$ | async)" class="submitButton" mat-raised-button color="primary" (click)=submit()>submit</button>

</mat-card>
